[package]
name = "php-parser-rs"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dev-dependencies]
pretty_assertions = "1.3.0"

[[bin]]
name = "integration-test"
path = "integration-test/run.rs"
